SELECT * FROM sys.indexes;
SELECT * FROM sys.index_columns;
SELECT * FROM sys.dm_db_index_usage_stats;
SELECT * FROM sys.objects;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'';